language: node_js
node_js:
  - 12

addons:
  sonarcloud:
    organization: "hirle-github"
    token:
      secure: "B6ys9TwCKowEH8U1Fe8svdCq+Gg8jncFNjOIU8cS84FfyDR9HxfXnuxHLG/eNA7xYXDJQLK+tMATgqIiPYG0iditONpxpVJTVC32GoEyiZygAxJ0ztancLgS0k215FqFhFD4d6ZVnFZReyQ4serFNkeyWoJzXYi+XFCPNwTnzh+/anffGWf3O8e1w+c+s5cI5iesTMUbbG1tpIRoVh2RIUtTNPcGUQFTW8eoV3p7Sz5byYpMFZZQZIZVzcUvOILeMdC0OvPnq8l9maGgFMOqPRxyepYgrYEnOePF7KOEhttfRSbclyB7npHFl9OwZmUVN3CWr+W3DJdnI4gmsPmgheYk7otB+ONru4vkFmjl7q/pl6IKu282A5pQOh20XGkTH0yxeHgGhvMVHi1u4V1UoaZC9+G2UIYOzFnEkTPT9i6qCLYJ1uTdmm+sDuicaMRTnRzfeS2pO7Llhs+IGw0dHP378lZ/rWB/JTb0Ct0JhqRwbaVrTYhlh1jzsKE25FknBD1tJrbf0Oh0FNAUkbs10FwrV8C2VQOikBcdr0tuQ584vX45hqW3lFdYlKkVZzlo26tlj9RDWqriOOk+thpLZDqo/r5VB4HibyTixY5WWqwtGgxqcbizEBI5EBlcburONB+DWasoWkEbK1GOI1oisgYcjTgdcRoQZs71P94xZbs="

script:
  - yarn install
  - yarn coverage
  - sonar-scanner
